name: Zenix Auto Renew OCR

on:
  schedule:
    - cron: '0 16 * * *' # 12:00 AM PH Time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr chromium-browser

      - name: Install Python Packages
        run: |
          pip install undetected-chromedriver pytesseract Pillow selenium

      - name: Run Script
        env:
          ZENIX_RENEW_LINK: ${{ secrets.ZENIX_RENEW_LINK }}
        run: python renew.py
